enableVersioning: true
handle: scratch
name: scratch
propagationMethod: all
siteSettings:
  4a08a421-ed5e-4eb5-8dbc-018aed34c7d3:
    enabledByDefault: true
    hasUrls: true
    template: singles/scratch
    uriFormat: scratch
type: single
